# Generated by Django 5.2.14 on 2026-05-17 16:01

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_featured_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_video',
            field=models.FileField(blank=True, null=True, storage=core.storage.SolakutiVideoCloudinaryStorage(), upload_to='articles/videos/'),
        ),
    ]
