# Generated by Django 5.2.14 on 2026-05-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_articlesportslink'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='articlesportslink',
            new_name='news_articl_target__bb5078_idx',
            old_name='news_articl_target__8cae98_idx',
        ),
        migrations.RenameIndex(
            model_name='articlesportslink',
            new_name='news_articl_target__04f906_idx',
            old_name='news_articl_target__ad42fc_idx',
        ),
    ]
