# Generated by Django 5.2.14 on 2026-05-17 16:01

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(storage=core.storage.MixedMediaCloudinaryStorage(), upload_to='uploads/'),
        ),
    ]
