# Generated by Django 5.2.14 on 2026-05-23 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportsSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=80)),
                ('task', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('logo_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='sports_comp_slug_73decd_idx'), models.Index(fields=['provider', 'provider_id'], name='sports_comp_provide_856a3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('crest_url', models.URLField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='sports_team_slug_a6b7ef_idx'), models.Index(fields=['provider', 'provider_id'], name='sports_team_provide_b0ed62_idx')],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('halftime', 'Half-time'), ('finished', 'Finished'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_score', models.PositiveSmallIntegerField(default=0)),
                ('away_score', models.PositiveSmallIntegerField(default=0)),
                ('venue', models.CharField(blank=True, max_length=160)),
                ('round_name', models.CharField(blank=True, max_length=120)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixtures', to='sports.competition')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_fixtures', to='sports.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_fixtures', to='sports.team')),
            ],
            options={
                'ordering': ['kickoff_at', 'competition__name'],
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('played', models.PositiveSmallIntegerField(default=0)),
                ('won', models.PositiveSmallIntegerField(default=0)),
                ('drawn', models.PositiveSmallIntegerField(default=0)),
                ('lost', models.PositiveSmallIntegerField(default=0)),
                ('goals_for', models.PositiveSmallIntegerField(default=0)),
                ('goals_against', models.PositiveSmallIntegerField(default=0)),
                ('goal_difference', models.SmallIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('form', models.CharField(blank=True, max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='sports.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='sports.team')),
            ],
            options={
                'ordering': ['competition', 'position'],
                'indexes': [models.Index(fields=['competition', 'position'], name='sports_stan_competi_59c17f_idx')],
                'unique_together': {('competition', 'team')},
            },
        ),
        migrations.CreateModel(
            name='FixtureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('card', 'Card'), ('substitution', 'Substitution'), ('var', 'VAR'), ('info', 'Info')], db_index=True, max_length=30)),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('player_name', models.CharField(blank=True, max_length=160)),
                ('detail', models.CharField(blank=True, max_length=220)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sports.fixture')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixture_events', to='sports.team')),
            ],
            options={
                'ordering': ['minute', 'created_at'],
                'indexes': [models.Index(fields=['fixture', 'minute'], name='sports_fixt_fixture_7683e0_idx'), models.Index(fields=['event_type'], name='sports_fixt_event_t_f50040_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['status', 'kickoff_at'], name='sports_fixt_status_541358_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['kickoff_at'], name='sports_fixt_kickoff_a0829f_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['provider', 'provider_id'], name='sports_fixt_provide_0def4d_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['is_featured', 'kickoff_at'], name='sports_fixt_is_feat_63448b_idx'),
        ),
    ]
