# Generated by Django 5.2.14 on 2026-05-24 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=180)),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=40)),
                ('formation_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_starting', models.BooleanField(db_index=True, default=True)),
                ('is_captain', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=120)),
            ],
            options={
                'ordering': ['team', '-is_starting', 'formation_position', 'shirt_number', 'player_name'],
            },
        ),
        migrations.CreateModel(
            name='FixtureMomentum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveSmallIntegerField()),
                ('home_value', models.SmallIntegerField(default=0)),
                ('away_value', models.SmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='FixtureStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('home_value', models.CharField(blank=True, max_length=40)),
                ('away_value', models.CharField(blank=True, max_length=40)),
                ('home_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('away_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('position', models.CharField(choices=[('goalkeeper', 'Goalkeeper'), ('defender', 'Defender'), ('midfielder', 'Midfielder'), ('forward', 'Forward'), ('coach', 'Coach'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30)),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_year', 'competition__name'],
            },
        ),
        migrations.CreateModel(
            name='SquadMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('left_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['team', 'shirt_number', 'player__name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('surface', models.CharField(blank=True, max_length=80)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='standing',
            name='sports_stan_competi_59c17f_idx',
        ),
        migrations.AddField(
            model_name='fixture',
            name='attendance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_formation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_manager',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_xg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_formation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_manager',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_xg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='injury_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='period',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='fixture',
            name='referee',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='fixture',
            name='status_reason',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='fixtureevent',
            name='assist_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='fixtureevent',
            name='away_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixtureevent',
            name='extra_minute',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixtureevent',
            name='home_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixtureevent',
            name='period',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='fixtureevent',
            name='provider',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='fixtureevent',
            name='provider_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fixtureevent',
            name='related_player_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='fixtureevent',
            name='event_type',
            field=models.CharField(choices=[('goal', 'Goal'), ('card', 'Card'), ('substitution', 'Substitution'), ('var', 'VAR'), ('penalty', 'Penalty'), ('missed_penalty', 'Missed penalty'), ('own_goal', 'Own goal'), ('red_card', 'Red card'), ('yellow_card', 'Yellow card'), ('period', 'Period'), ('info', 'Info')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='fixtureevent',
            index=models.Index(fields=['provider', 'provider_id'], name='sports_fixt_provide_eb68a3_idx'),
        ),
        migrations.AddField(
            model_name='fixturelineup',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='sports.fixture'),
        ),
        migrations.AddField(
            model_name='fixturelineup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_lineups', to='sports.team'),
        ),
        migrations.AddField(
            model_name='fixturemomentum',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentum', to='sports.fixture'),
        ),
        migrations.AddField(
            model_name='fixturestatistic',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='sports.fixture'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='sports.team'),
        ),
        migrations.AddField(
            model_name='fixturelineup',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixture_lineups', to='sports.player'),
        ),
        migrations.AddField(
            model_name='season',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='sports.competition'),
        ),
        migrations.AlterUniqueTogether(
            name='standing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fixture',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='sports.season'),
        ),
        migrations.AddField(
            model_name='standing',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standings', to='sports.season'),
        ),
        migrations.AlterUniqueTogether(
            name='standing',
            unique_together={('competition', 'season', 'team')},
        ),
        migrations.AddIndex(
            model_name='standing',
            index=models.Index(fields=['competition', 'season', 'position'], name='sports_stan_competi_75a240_idx'),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_memberships', to='sports.player'),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_memberships', to='sports.season'),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_memberships', to='sports.team'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['slug'], name='sports_venu_slug_7405da_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['provider', 'provider_id'], name='sports_venu_provide_adb9f8_idx'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='venue_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='sports.venue'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['competition', 'season', 'kickoff_at'], name='sports_fixt_competi_eb2100_idx'),
        ),
        migrations.AddIndex(
            model_name='fixturemomentum',
            index=models.Index(fields=['fixture', 'minute'], name='sports_fixt_fixture_d1aacd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fixturemomentum',
            unique_together={('fixture', 'minute')},
        ),
        migrations.AddIndex(
            model_name='fixturestatistic',
            index=models.Index(fields=['fixture', 'group'], name='sports_fixt_fixture_539deb_idx'),
        ),
        migrations.AddIndex(
            model_name='fixturestatistic',
            index=models.Index(fields=['provider', 'provider_id'], name='sports_fixt_provide_88f7bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fixturestatistic',
            unique_together={('fixture', 'group', 'name')},
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['slug'], name='sports_play_slug_209562_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['provider', 'provider_id'], name='sports_play_provide_ec6a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['current_team', 'position'], name='sports_play_current_2a514c_idx'),
        ),
        migrations.AddIndex(
            model_name='fixturelineup',
            index=models.Index(fields=['fixture', 'team', 'is_starting'], name='sports_fixt_fixture_28f05c_idx'),
        ),
        migrations.AddIndex(
            model_name='fixturelineup',
            index=models.Index(fields=['player'], name='sports_fixt_player__126ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='fixturelineup',
            index=models.Index(fields=['provider', 'provider_id'], name='sports_fixt_provide_2b0a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['competition', 'is_current'], name='sports_seas_competi_3b0e74_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['provider', 'provider_id'], name='sports_seas_provide_9dbff6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('competition', 'name')},
        ),
        migrations.AddIndex(
            model_name='squadmembership',
            index=models.Index(fields=['team', 'season'], name='sports_squa_team_id_039d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='squadmembership',
            index=models.Index(fields=['player'], name='sports_squa_player__15116c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='squadmembership',
            unique_together={('team', 'season', 'player')},
        ),
    ]
